### ISSUE TITLE
problem importing from my backup

### ISSUE THREAD

**Issue by 0lzi** [gregsowell/ascender-configuration-as-code-migration#5]
I run the backup and pull all the files from the config folder and put them into my private repo, when I try and import it fails
```
TASK [Job templates fix - Convert extra_vars in each job template to a dictionary] ***
task path: /runner/project/import.yml:169
```

my job_templates.yml
```


    job_templates:
    -   allow_simultaneous: false
        ask_credential_on_launch: false
        ask_diff_mode_on_launch: false
        ask_execution_environment_on_launch: false
        ask_forks_on_launch: false
        ask_instance_groups_on_launch: false
        ask_inventory_on_launch: true
        ask_job_slice_count_on_launch: false
        ask_job_type_on_launch: false
        ask_labels_on_launch: false
        ask_limit_on_launch: false
        ask_scm_branch_on_launch: false
        ask_skip_tags_on_launch: false
        ask_tags_on_launch: false
        ask_timeout_on_launch: false
        ask_variables_on_launch: false
        ask_verbosity_on_launch: false
        become_enabled: false
        description: ''
        diff_mode: false
        execution_environment: null
        extra_vars: '

            export_host: awx.local

            gen1_user: oli

            gen1_pword: ********

            repo_dir: /media/usb-storage/awx-config/configs'
        force_handlers: false
        forks: 0
        host_config_key: ''
        inventory: null
        job_slice_count: 1
        job_tags: ''
        job_type: run
        limit: ''
        name: AWX backup
        natural_key:
            name: AWX backup
            organization:
                name: Default
                type: organization
            type: job_template
        playbook: export.yml
        prevent_instance_group_fallback: false
        project:
            name: AWX-CaC
            organization:
                name: Default
                type: organization
            type: project
        related:
            credentials:
            -   credential_type:
                    kind: ssh
                    name: Machine
                    type: credential_type
                name: Pi
                organization: null
                type: credential
            labels: []
            notification_templates_error: []
            notification_templates_started: []
            notification_templates_success: []
            schedules: []
            survey_spec: {}
        scm_branch: ''
        skip_tags: ''
        start_at_task: ''
        survey_enabled: false
        timeout: 0
        use_fact_cache: false
        verbosity: 0
        webhook_credential: null
        webhook_service: ''
    -   allow_simultaneous: false
        ask_credential_on_launch: false
        ask_diff_mode_on_launch: false
        ask_execution_environment_on_launch: false
        ask_forks_on_launch: false
        ask_instance_groups_on_launch: false
        ask_inventory_on_launch: true
        ask_job_slice_count_on_launch: false
        ask_job_type_on_launch: false
        ask_labels_on_launch: false
        ask_limit_on_launch: false
        ask_scm_branch_on_launch: false
        ask_skip_tags_on_launch: false
        ask_tags_on_launch: false
        ask_timeout_on_launch: false
        ask_variables_on_launch: false
        ask_verbosity_on_launch: false
        become_enabled: false
        description: ''
        diff_mode: false
        execution_environment: null
        extra_vars: '

            export_host: awx.local

            gen1_user: oli

            gen1_pword: ********

            repo_dir: /media/usb-storage/ascender-configuration-as-code-migration/configs'
        force_handlers: false
        forks: 0
        host_config_key: ''
        inventory: null
        job_slice_count: 1
        job_tags: ''
        job_type: run
        limit: ''
        name: AWX backup - DEV
        natural_key:
            name: AWX backup - DEV
            organization:
                name: Default
                type: organization
            type: job_template
        playbook: export.yml
        prevent_instance_group_fallback: false
        project:
            name: Ascender as code
            organization:
                name: Default
                type: organization
            type: project
        related:
            credentials:
            -   credential_type:
                    kind: ssh
                    name: Machine
                    type: credential_type
                name: Pi
                organization: null
                type: credential
            labels: []
            notification_templates_error: []
            notification_templates_started: []
            notification_templates_success: []
            schedules: []
            survey_spec: {}
        scm_branch: ''
        skip_tags: ''
        start_at_task: ''
        survey_enabled: false
        timeout: 0
        use_fact_cache: false
        verbosity: 0
        webhook_credential: null
        webhook_service: ''
    -   allow_simultaneous: false
        ask_credential_on_launch: false
        ask_diff_mode_on_launch: false
        ask_execution_environment_on_launch: false
        ask_forks_on_launch: false
        ask_instance_groups_on_launch: false
        ask_inventory_on_launch: true
        ask_job_slice_count_on_launch: false
        ask_job_type_on_launch: false
        ask_labels_on_launch: false
        ask_limit_on_launch: false
        ask_scm_branch_on_launch: false
        ask_skip_tags_on_launch: false
        ask_tags_on_launch: false
        ask_timeout_on_launch: false
        ask_variables_on_launch: false
        ask_verbosity_on_launch: false
        become_enabled: false
        description: ''
        diff_mode: false
        execution_environment: null
        extra_vars: '

            import_host: awx.local

            gen2_user: oli

            gen2_pword: ********

            config_dir: /media/usb-storage/awx-config'
        force_handlers: false
        forks: 0
        host_config_key: ''
        inventory: null
        job_slice_count: 1
        job_tags: ''
        job_type: run
        limit: ''
        name: AWX-Import
        natural_key:
            name: AWX-Import
            organization:
                name: Default
                type: organization
            type: job_template
        playbook: import.yml
        prevent_instance_group_fallback: false
        project:
            name: Ascender as code
            organization:
                name: Default
                type: organization
            type: project
        related:
            credentials:
            -   credential_type:
                    kind: ssh
                    name: Machine
                    type: credential_type
                name: Pi
                organization: null
                type: credential
            labels: []
            notification_templates_error: []
            notification_templates_started: []
            notification_templates_success: []
            schedules: []
            survey_spec: {}
        scm_branch: ''
        skip_tags: ''
        start_at_task: ''
        survey_enabled: false
        timeout: 0
        use_fact_cache: false
        verbosity: 2
        webhook_credential: null
        webhook_service: ''
    -   allow_simultaneous: false
        ask_credential_on_launch: false
        ask_diff_mode_on_launch: false
        ask_execution_environment_on_launch: false
        ask_forks_on_launch: false
        ask_instance_groups_on_launch: false
        ask_inventory_on_launch: true
        ask_job_slice_count_on_launch: false
        ask_job_type_on_launch: false
        ask_labels_on_launch: false
        ask_limit_on_launch: false
        ask_scm_branch_on_launch: false
        ask_skip_tags_on_launch: false
        ask_tags_on_launch: false
        ask_timeout_on_launch: false
        ask_variables_on_launch: false
        ask_verbosity_on_launch: true
        become_enabled: false
        description: ''
        diff_mode: false
        execution_environment: null
        extra_vars: '

            import_host: awx.local

            gen2_user: oli

            gen2_pword: ********

            #config_dir: /media/usb-storage/awx-config'
        force_handlers: false
        forks: 0
        host_config_key: ''
        inventory: null
        job_slice_count: 1
        job_tags: ''
        job_type: run
        limit: ''
        name: AWX-Import - DEV
        natural_key:
            name: AWX-Import - DEV
            organization:
                name: Default
                type: organization
            type: job_template
        playbook: import.yml
        prevent_instance_group_fallback: false
        project:
            name: AWX-CaC
            organization:
                name: Default
                type: organization
            type: project
        related:
            credentials:
            -   credential_type:
                    kind: ssh
                    name: Machine
                    type: credential_type
                name: Pi
                organization: null
                type: credential
            labels: []
            notification_templates_error: []
            notification_templates_started: []
            notification_templates_success: []
            schedules: []
            survey_spec: {}
        scm_branch: ''
        skip_tags: ''
        start_at_task: ''
        survey_enabled: false
        timeout: 0
        use_fact_cache: false
        verbosity: 2
        webhook_credential: null
        webhook_service: ''
    -   allow_simultaneous: false
        ask_credential_on_launch: false
        ask_diff_mode_on_launch: false
        ask_execution_environment_on_launch: false
        ask_forks_on_launch: false
        ask_instance_groups_on_launch: false
        ask_inventory_on_launch: false
        ask_job_slice_count_on_launch: false
        ask_job_type_on_launch: false
        ask_labels_on_launch: false
        ask_limit_on_launch: false
        ask_scm_branch_on_launch: false
        ask_skip_tags_on_launch: false
        ask_tags_on_launch: false
        ask_timeout_on_launch: false
        ask_variables_on_launch: false
        ask_verbosity_on_launch: false
        become_enabled: false
        description: ''
        diff_mode: false
        execution_environment: null
        extra_vars: ''
        force_handlers: false
        forks: 0
        host_config_key: ''
        inventory:
            name: Demo Inventory
            organization:
                name: Default
                type: organization
            type: inventory
        job_slice_count: 1
        job_tags: ''
        job_type: run
        limit: ''
        name: Demo Job Template
        natural_key:
            name: Demo Job Template
            organization:
                name: Default
                type: organization
            type: job_template
        playbook: hello_world.yml
        prevent_instance_group_fallback: false
        project:
            name: Demo Project
            organization:
                name: Default
                type: organization
            type: project
        related:
            credentials:
            -   credential_type:
                    kind: ssh
                    name: Machine
                    type: credential_type
                name: Demo Credential
                organization: null
                type: credential
            labels: []
            notification_templates_error: []
            notification_templates_started: []
            notification_templates_success: []
            schedules: []
            survey_spec: {}
        scm_branch: ''
        skip_tags: ''
        start_at_task: ''
        survey_enabled: false
        timeout: 0
        use_fact_cache: false
        verbosity: 0
        webhook_credential: null
        webhook_service: ''
    -   allow_simultaneous: false
        ask_credential_on_launch: false
        ask_diff_mode_on_launch: false
        ask_execution_environment_on_launch: false
        ask_forks_on_launch: false
        ask_instance_groups_on_launch: false
        ask_inventory_on_launch: false
        ask_job_slice_count_on_launch: false
        ask_job_type_on_launch: false
        ask_labels_on_launch: false
        ask_limit_on_launch: false
        ask_scm_branch_on_launch: false
        ask_skip_tags_on_launch: false
        ask_tags_on_launch: false
        ask_timeout_on_launch: false
        ask_variables_on_launch: false
        ask_verbosity_on_launch: false
        become_enabled: false
        description: ''
        diff_mode: false
        execution_environment: null
        extra_vars: ''
        force_handlers: false
        forks: 0
        host_config_key: ''
        inventory:
            name: Pi
            organization:
                name: Default
                type: organization
            type: inventory
        job_slice_count: 1
        job_tags: ''
        job_type: run
        limit: ''
        name: Demo Playbook Template
        natural_key:
            name: Demo Playbook Template
            organization:
                name: Default
                type: organization
            type: job_template
        playbook: playbooks/update/main.yml
        prevent_instance_group_fallback: false
        project:
            name: Demo Playbook project
            organization:
                name: Default
                type: organization
            type: project
        related:
            credentials:
            -   credential_type:
                    kind: ssh
                    name: Machine
                    type: credential_type
                name: Pi Password
                organization: null
                type: credential
            labels: []
            notification_templates_error: []
            notification_templates_started: []
            notification_templates_success: []
            schedules:
            -   description: update raspberry pi
                diff_mode: null
                enabled: true
                execution_environment: null
                extra_data: {}
                forks: null
                inventory:
                    name: Pi
                    organization:
                        name: Default
                        type: organization
                    type: inventory
                job_slice_count: null
                job_tags: null
                job_type: null
                limit: null
                name: pi updates
                natural_key:
                    name: pi updates
                    type: schedule
                    unified_job_template:
                        name: Demo Playbook Template
                        organization:
                            name: Default
                            type: organization
                        type: job_template
                related:
                    credentials: []
                rrule: DTSTART;TZID=Europe/London:20231122T070500
                    RRULE:INTERVAL=1;FREQ=MONTHLY;BYMONTHDAY=22
                scm_branch: null
                skip_tags: null
                timeout: null
                unified_job_template:
                    name: Demo Playbook Template
                    organization:
                        name: Default
                        type: organization
                    type: job_template
                verbosity: null
            survey_spec: {}
        scm_branch: ''
        skip_tags: ''
        start_at_task: ''
        survey_enabled: false
        timeout: 0
        use_fact_cache: false
        verbosity: 0
        webhook_credential: null
        webhook_service: ''

```

When I run your import from your repo it pulls in fine so the issue would point to this file in particular. have uploaded debug log from that job with redacted info but im a bit stumped on the error its spitting out.

[job_107.txt](https://github.com/gregsowell/ascender-configuration-as-code-migration/files/13503966/job_107.txt)
